name: magma bazel build
on: [push]
jobs:
  bazel-build:
    runs-on: ubuntu-latest
    steps:
    - run: |
        export MAGMA_ROOT=${PWD}/magma
        git clone https://github.com/magma/magma.git --depth 1
        cd magma/experimental/bazel-base/
        docker-compose build magma-builder
        docker images

