name: magma bazel build
on: [push]
jobs:
  bazel-build:
    runs-on: ubuntu-latest
    steps:
    - uses: docker/login-action@v1 
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
    - run: |
        export MAGMA_ROOT=${PWD}/magma
        git clone https://github.com/magma/magma.git --depth 1
        cd magma/experimental/bazel-base/
        docker-compose build magma-builder
        docker images
        docker tag bazel-base_magma-builder nani903020/bazel-base_magma-builder
        docker push nani903020/bazel-base_magma-builder
